development: &defaults
  default_url: 'localhost:5000'
  locale_app_polling_environments: 'production'
  locale_app_sending_environments: 'production'
  auth_user: admin
  auth_password: password

test:
  <<: *defaults

production:
  <<: *defaults
  default_url: 'localhost'
